name: Get Sentiment and update GitHub page

on:
  schedule:
    - cron: "*/30 * * * *" # runs every half hour
    
jobs:
  refresh_page:
    runs-on: ubuntu-latest    
    steps:
      - name: Access the repo
        uses: actions/checkout@v2 
    
      - name: Configure Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10' 
      
      - name: Install necessary libraries
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Execute python script to update sentiment page
        run: python update_sentiment_page.py
        
      - name: Clone repo from your github.io page and commit newly generated sentiment html file
        run: | #change all the "damianboh"s below to your username
          git clone https://github.com/kcwhite/kcwhite.github.io.git/ 
          cp dow_jones_live_sentiment.html kcwhite.github.io/dow_jones_live_sentiment.html 
          cd kcwhite.github.io 
          git add dow_jones_live_sentiment.html
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m 'refresh dow jones sentiment page'        
        
      - name: Push updated html to github.io page
        uses: ad-m/github-push-action@master
        with: #change all the "damianboh"s below to your username
          github_token: ${{ secrets.TOKEN }}          
          repository: "kcwhite/kcwhite.github.io"
          branch: "main"          
          directory: ./kcwhite.github.io
          
        
